name: "Security Code Scan"

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '12 9 * * 4'

jobs:
  SCS:
    runs-on: windows-2019
    steps:     
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'  
      - uses: nuget/setup-nuget@v1.0.5
      - uses: microsoft/setup-msbuild@v1.0.2

      - name: Set up projects
        uses: security-code-scan/security-code-scan-add-action@main

      - name: Build
        run: |
          nuget restore
          msbuild
        
      - name: Convert sarif for uploading to GitHub
        #uses: felickz/StyleCopAnalyzers-results-action@patch-1
        uses: security-code-scan/security-code-scan-results-action@main
        
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v3
